### ISSUE TITLE
通过菜单设置开机自启动失败

### ISSUE THREAD

**Issue by Colin5887** [pluveto/Caplos#1]
通过右键菜单设置开机自启动后，重启电脑，软件并没有自启动。猜测原因是程序并没有`以管理员身份运行`，导致程序缺少权限操纵注册表。我自己有一个程序就会出现这样的问题。

但是看了您的代码，并没有发现空的try-catch，但是程序也没有报错退出，感觉很奇怪。

我并不知道具体的原因是什么，所以在这里给您留一个issue，如果您时间方便的话，可以看一下这个问题。

**Comment by pluveto** [comment]
你好, 已在新版本修此问题. 查看注册表发现所需条目能够添加. 你可以[下载](https://www.lanzous.com/i9o4asf)并测试. 如果发现还是不行, 建议把软件放在 `C:\` 之外的分区.

如果问题解决, 可关闭此 issue.

**Comment by Colin5887** [comment]
谢谢，问题已经解决，而且新版本中的那些debug模式下的文件也移除了，非常感谢
