### ISSUE TITLE
Caplos启动后系统内会莫名出现隐藏的帮助窗口

### ISSUE THREAD

**Issue by monologconnor** [pluveto/Caplos#14]
程序启动后会在窗口列表中出现未显示在任务栏中的帮助窗口
![image](https://user-images.githubusercontent.com/38450642/122821547-8ee0cf00-d30f-11eb-987c-8d530bd3352c.png)

打开后是Caplos的帮助文档窗口
![image](https://user-images.githubusercontent.com/38450642/122821565-986a3700-d30f-11eb-932e-71b006e07c09.png)

**Comment by pluveto** [comment]
现在可以了吗？

**Comment by monologconnor** [comment]
> 现在可以了吗？

更新后我这边已经修复了
感谢
