### ISSUE TITLE
virustotal MaxSecure Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by iuriimattos2** [pluveto/Caplos#15]
我相信这是误报
https://www.virustotal.com/gui/file/10b9d13fa05d9f2a61b4c826e2754f89962453e0de4ae76a14cdc20f672c4576

没有误报的版本可能吗？

@pluveto @Zeroto521 
感谢您分享您的知识

:)

**Comment by pluveto** [comment]
This software use Win32 API to listen key events such as capslock pressed.
If you're worried about this, you can compile your own binary or look into the assembly code to figure out the truth.
