### ISSUE TITLE
Shift键无法与软件一同使用

### ISSUE THREAD

**Issue by Colin5887** [pluveto/Caplos#2]
本来想看看能不能自家加入这个功能，看了看源代码找不到思路，抱歉又过来骚扰作者了。

需求是这样的，我经常会按住Shift键，然后使用上下左右方向键来选择文本。不过通过`Caplos`，在按住CapsLock键，再加上上下左右的替换键，再按住Shift，这时候只会移动光标的位置，无法在移动光标的时候同时选中文本。

这个功能方便实现吗？

**Comment by pluveto** [comment]
你好, 刚才修复了这个问题. 新版本可[在此](https://www.lanzous.com/i9zzbvg)下载. 如果问题仍然存在可继续反馈, 如果解决可关闭此 issue.

**Comment by Colin5887** [comment]
谢谢，`Caplos-3-6`版本中问题已经修复，功能正常
