### ISSUE TITLE
下载编译好的二进制文件的情况下，如何自定义按键？

### ISSUE THREAD

**Issue by solxnp** [pluveto/Caplos#7]

**Comment by pluveto** [comment]
首次运行之后，会生成一个配置文件，编辑该配置文件即可。

**Comment by solxnp** [comment]
@pluveto 
配置文件是指Caplos.exe.config吗？（目录下只有 .cfg、.exe、.exe.confg、.pdb四个文件）
如果是的话，它的内容只有以下，我不知道该如何编辑自定义
![image](https://user-images.githubusercontent.com/18416053/88147170-6ea41e00-cc2f-11ea-8c68-225ed2d2c3af.png)

**Comment by pluveto** [comment]
请编辑 cfg 文件
